spring.datasource.url=jdbc:postgresql://localhost:5432/telegram_bot
spring.datasource.username=bot_user
spring.datasource.password=student
telegram.bot.token=7511373505:AAEG1-oaIfTFCDE_ADiRr_W1cyeATeq2Yh4
server.port=8080

